"""judgments: add source, source_id, year

Revision ID: 10811d8a72b4
Revises: c6f34da27cba
Create Date: 2026-08-06 01:12:49.902973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10811d8a72b4"
down_revision: Union[str, Sequence[str], None] = "c6f34da27cba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bns_mapping_source"), table_name="bns_mapping")
    op.drop_index(op.f("ix_bns_mapping_source_id"), table_name="bns_mapping")
    op.drop_index(op.f("ix_bns_mapping_year"), table_name="bns_mapping")
    op.drop_column("bns_mapping", "source")
    op.drop_column("bns_mapping", "year")
    op.drop_column("bns_mapping", "source_id")
    op.add_column("judgments", sa.Column("source", sa.String(length=50), nullable=True))
    op.add_column(
        "judgments", sa.Column("source_id", sa.String(length=100), nullable=True)
    )
    op.add_column("judgments", sa.Column("year", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_judgments_source"), "judgments", ["source"], unique=False)
    op.create_index(
        op.f("ix_judgments_source_id"), "judgments", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_judgments_year"), "judgments", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_judgments_year"), table_name="judgments")
    op.drop_index(op.f("ix_judgments_source_id"), table_name="judgments")
    op.drop_index(op.f("ix_judgments_source"), table_name="judgments")
    op.drop_column("judgments", "year")
    op.drop_column("judgments", "source_id")
    op.drop_column("judgments", "source")
    op.add_column(
        "bns_mapping",
        sa.Column(
            "source_id", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "bns_mapping",
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "bns_mapping",
        sa.Column("source", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.create_index(op.f("ix_bns_mapping_year"), "bns_mapping", ["year"], unique=False)
    op.create_index(
        op.f("ix_bns_mapping_source_id"), "bns_mapping", ["source_id"], unique=False
    )
    op.create_index(
        op.f("ix_bns_mapping_source"), "bns_mapping", ["source"], unique=False
    )
    # ### end Alembic commands ###
