"""bns_mapping: nullable sections, add offence and category

Revision ID: 1797fb2c7556
Revises: b021439159ae
Create Date: 2026-08-06 00:13:18.228530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1797fb2c7556"
down_revision: Union[str, Sequence[str], None] = "b021439159ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bns_mapping", sa.Column("offence", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "bns_mapping", sa.Column("category", sa.String(length=100), nullable=True)
    )
    op.alter_column(
        "bns_mapping", "ipc_section", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "bns_mapping", "bns_section", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bns_mapping",
        "bns_section",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.alter_column(
        "bns_mapping",
        "ipc_section",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.drop_column("bns_mapping", "category")
    op.drop_column("bns_mapping", "offence")
    # ### end Alembic commands ###
