"""create initial tables

Revision ID: b021439159ae
Revises:
Create Date: 2026-07-28 21:29:18.044727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b021439159ae"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bns_mapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ipc_section", sa.String(length=50), nullable=False),
        sa.Column("bns_section", sa.String(length=50), nullable=False),
        sa.Column("ipc_text", sa.Text(), nullable=True),
        sa.Column("bns_text", sa.Text(), nullable=True),
        sa.Column("change_type", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bns_mapping_bns_section"), "bns_mapping", ["bns_section"], unique=False
    )
    op.create_index(
        op.f("ix_bns_mapping_ipc_section"), "bns_mapping", ["ipc_section"], unique=False
    )
    op.create_table(
        "judgments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("court", sa.String(length=255), nullable=False),
        sa.Column("case_no", sa.String(length=255), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("judgment_date", sa.DateTime(), nullable=True),
        sa.Column("full_text", sa.Text(), nullable=True),
        sa.Column("jsonb_meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_judgments_case_no"), "judgments", ["case_no"], unique=False
    )
    op.create_index(op.f("ix_judgments_court"), "judgments", ["court"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_pw", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("resource", sa.String(length=255), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("ts", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False
    )
    op.create_table(
        "judgment_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("judgment_id", sa.Integer(), nullable=False),
        sa.Column("chunk_idx", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True
        ),
        sa.ForeignKeyConstraint(["judgment_id"], ["judgments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_judgment_chunks_judgment_id"),
        "judgment_chunks",
        ["judgment_id"],
        unique=False,
    )
    op.create_table(
        "user_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_cases_user_id"), "user_cases", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_cases_user_id"), table_name="user_cases")
    op.drop_table("user_cases")
    op.drop_index(op.f("ix_judgment_chunks_judgment_id"), table_name="judgment_chunks")
    op.drop_table("judgment_chunks")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_judgments_court"), table_name="judgments")
    op.drop_index(op.f("ix_judgments_case_no"), table_name="judgments")
    op.drop_table("judgments")
    op.drop_index(op.f("ix_bns_mapping_ipc_section"), table_name="bns_mapping")
    op.drop_index(op.f("ix_bns_mapping_bns_section"), table_name="bns_mapping")
    op.drop_table("bns_mapping")
    # ### end Alembic commands ###
