"""judgments: add source, source_id, year

Revision ID: c6f34da27cba
Revises: 1797fb2c7556
Create Date: 2026-08-06 01:09:57.620182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c6f34da27cba"
down_revision: Union[str, Sequence[str], None] = "1797fb2c7556"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bns_mapping", sa.Column("source", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "bns_mapping", sa.Column("source_id", sa.String(length=100), nullable=True)
    )
    op.add_column("bns_mapping", sa.Column("year", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_bns_mapping_source"), "bns_mapping", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_bns_mapping_source_id"), "bns_mapping", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_bns_mapping_year"), "bns_mapping", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bns_mapping_year"), table_name="bns_mapping")
    op.drop_index(op.f("ix_bns_mapping_source_id"), table_name="bns_mapping")
    op.drop_index(op.f("ix_bns_mapping_source"), table_name="bns_mapping")
    op.drop_column("bns_mapping", "year")
    op.drop_column("bns_mapping", "source_id")
    op.drop_column("bns_mapping", "source")
    # ### end Alembic commands ###
